# Generated by Django 4.2.7 on 2023-11-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_admin_department_semester_subject_teacher_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='emailid',
            field=models.EmailField(max_length=254),
        ),
    ]
