# Generated by Django 4.2.7 on 2023-12-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_admin_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacherName',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
