# Generated by Django 4.2.1 on 2023-12-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_teachername_teacher_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='acoe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='empid',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phoneNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Hod',
        ),
    ]
