# Generated by Django 4.2.1 on 2023-12-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='Subject_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='programme',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
